using System;
using NUnit.Framework;
using ContosoCrafts.WebSite.Models;
using System.Text.Json;

namespace UnitTests.Models
{
    /// <summary>
    /// Unit tests for the CommentModel class following project test conventions.
    /// </summary>
    [TestFixture]
    public class CommentModelTest
    {
        #region Constructor Tests

        /// <summary>
        /// Tests that default constructor sets ID to non-empty value and Comment to empty string.
        /// </summary>
        [Test]
        public void Constructor_NoArgs_DefaultsSet_IdNotEmptyAndCommentEmpty_Expected()
        {
            // Arrange
            var TestData = new { /* no setup values needed for default constructor */ };

            // Act
            var CommentModel = new CommentModel();
            var Id = CommentModel.Id;
            var Comment = CommentModel.Comment;

            // Reset
            CommentModel = null;

            // Assert
            Assert.AreNotEqual(null, Id);
            Assert.AreNotEqual(string.Empty, Id);
            Assert.AreEqual(string.Empty, Comment);
        }

        #endregion

        #region Property Tests

        /// <summary>
        /// Tests that property setters work correctly and reflect assigned values.
        /// </summary>
        [Test]
        public void Setters_AssignValues_PropertiesReflectChanges_IdAndCommentUpdated_Expected()
        {
            // Arrange
            var TestData = new { text = "Test comment", id = "custom-id" };

            // Act
            var CommentModel = new CommentModel();
            CommentModel.Comment = TestData.text;
            CommentModel.Id = TestData.id;
            var Id = CommentModel.Id;
            var Comment = CommentModel.Comment;

            // Reset
            CommentModel = null;

            // Assert
            Assert.AreEqual(TestData.text, Comment);
            Assert.AreEqual(TestData.id, Id);
        }

        /// <summary>
        /// Tests that ID generated by constructor is a valid GUID.
        /// </summary>
        [Test]
        public void Id_AfterConstruction_IsValidGuid_Expected()
        {
            // Arrange - none

            // Act
            var CommentModel = new CommentModel();
            var Id = CommentModel.Id;

            // Reset
            CommentModel = null;

            // Assert
            Assert.AreEqual(true, Guid.TryParse(Id, out _));
        }

        /// <summary>
        /// Tests that Comment property allows null values.
        /// </summary>
        [Test]
        public void Comment_SetToNull_AllowsNull_Expected()
        {
            // Arrange
            var CommentModel = new CommentModel();

            // Act
            CommentModel.Comment = null;
            var Comment = CommentModel.Comment;

            // Reset
            CommentModel = null;

            // Assert
            Assert.AreEqual(null, Comment);
        }

        #endregion

        #region Serialization Tests

        /// <summary>
        /// Tests that CommentModel can be serialized and deserialized while preserving values.
        /// </summary>
        [Test]
        public void SerializeDeserialize_WhenSerializedAndDeserialized_PreservesValues_Expected()
        {
            // Arrange
            var CommentModel = new CommentModel();
            CommentModel.Comment = "integration comment";

            // Act
            var JsonContent = JsonSerializer.Serialize(CommentModel);
            var DeserializedModel = JsonSerializer.Deserialize<CommentModel>(JsonContent);

            // Reset
            CommentModel = null;

            // Assert
            Assert.AreEqual("integration comment", DeserializedModel.Comment);
            // Id should round-trip as string
            Assert.AreEqual(true, Guid.TryParse(DeserializedModel.Id, out _));
        }

        #endregion
    }
}
